### ISSUE TITLE
[ARM32/Linux] Enabling new ARM CI

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#10185]
Enabling new ARM CI

- [x] Prepare new ARM CI command (PR #9853)
       All nine command has been enabled.
       [Ubuntu-arm, Ununtu 16.04-arm, Tizen-armel] [Release, Checked, Debug]
- [x] Prepare new ARM CI using Docker  (Issue: #9273, PR: #9445)
- [x] Optimizing RootFS generation in new ARM CI (Issue: #9553, PR: #9445)
- [x] Enable new ARM CI as default
      We will enable four ARM CI as default, as disscussed at https://github.com/dotnet/core-setup/issues/790#issuecomment-281901627.
      - Ubuntu arm Release
      - Tizen armel Release
      - Ubuntu16.04 arm Debug
      - Tizen armel Debug

- [x] Disable old ARM CI using emulator

**Comment by hqueue** [comment]
New ARM CI is now enabled.
