### ISSUE TITLE
Linux symbol acquisition

### ISSUE THREAD

**Issue by lt72** [dotnet/coreclr#10419]
- [x] DESIGN: provide high level design for symbol acquisition from //symweb symbol server (.md)
- [x] DESIGN: list main components, their interaction, their extensibility points, and integration strategy for tools (e.g. debuggers, profilers, ...). Clearly list module to be added to distro.
- [x] implement library and basic testing 
- [x] integrate in dotnet CLI (see #14794) 
- [x] integrate in SOS (tracked by issue https://github.com/dotnet/diagnostics/issues/1 ) 
- [x] implement SOS integration testing (tracked by issue https://github.com/dotnet/diagnostics/issues/1 ) 
- [x] design tool acquisition through DLC

**Comment by mikem8361** [comment]
The dotnet CLI global symbol downloader extension is finished and published.

To get matching runtime and symbol binaries for the core dump use the symbol downloader CLI extension:
  - Install the [.NET Core 2.1 SDK](https://www.microsoft.com/net/download/).
  - Install the symbol downloader extension: `dotnet tool install -g dotnet-symbol`.
  - Run `dotnet symbol coredump` to download the runtime binaries and symbols.
  - Check out the coreclr and corefx repositories at the appropriate commit for the appropriate source.
  - For more details see: [dotnet-symbol](https://github.com/dotnet/symstore/blob/master/src/dotnet-symbol/README.md).
