### ISSUE TITLE
[Local GC] Local GC Feature Meta-Issue

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#11518]
This issue tracks all of the sub-issues related to Local GC on CoreCLR.

The current status of Local GC on CoreCLR:

1. With the `FEATURE_STANDALONE_GC` feature define, the VM can build such that it is capable of loading and running a standalone GC.
2. With the `FEATURE_STANDALONE_GC_ONLY` CMake feature define, the VM builds and links directly against a standalone GC.
3. The GC currently does not link when built as a shared library, but is very close.

Here's the list of known work items for getting a standalone GC off the ground and running (required for bare-minimum functionality):

* [ ] https://github.com/dotnet/coreclr/issues/11510 - [Local GC] Undefined symbol when building standalone: IsGCThread and IsGCThreadSpecial

* [ ] https://github.com/dotnet/coreclr/issues/11511 - [Local GC] Undefined symbols when building standalone: CPUGroupInfo and NumaNodeInfo

* [ ] https://github.com/dotnet/coreclr/issues/11512 - [Local GC] Undefined symbol when building standalone: g_SystemInfo

* [ ] https://github.com/dotnet/coreclr/issues/11513 - [Local GC] Undefined symbol when building standalone: g_TrapReturningThreads

This will allow a standalone GC to link as a shared library. From there we can begin testing our basic GC scenarios.

More advanced GC functionality (and performance) work items, required for shipping this feature but not for basic functionality:

* [ ] https://github.com/dotnet/coreclr/issues/8268 - Local GC: make the rest of diagnostics work. (The DAC portion is complete for non-handle-table purposes. The rest remains to be done.)

* [ ] https://github.com/dotnet/coreclr/issues/8362 - Local GC: GCToOSInterface platform detection. Performance is going to be terrible without this.

* [ ] https://github.com/dotnet/coreclr/issues/11514 - [Local GC] Enable feature: FEATURE_EVENT_TRACE

* [ ] https://github.com/dotnet/coreclr/issues/11515 - [Local GC] Enable feature: PROFILING_SUPPORTED

* [ ] https://github.com/dotnet/coreclr/issues/11516 - [Local GC] Enable feature: STRESS_HEAP
 
* [ ] https://github.com/dotnet/coreclr/issues/11517 - [Local GC] Enable feature: FEATURE_APPDOMAIN_RESOURCE_MONITORING

**Comment by swgillespie** [comment]
Update:

The GC does build as a shared library now and is mostly functional, pending a few bug fixes. The remaining work is to ensure that the GC can build without `FEATURE_REDHAWK` and that all diagnostics retain feature parity with a non-local GC. All of this must be done without regressing the performance or correctness of non-standalone GCs.

**Comment by swgillespie** [comment]
Tracking remaining issues:

* [Local GC Issue Query](https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=%5BLocal%20GC%5D%20in%3Atitle%20is%3Aissue%20is%3Aopen)
* [Local GC PR Query](https://github.com/dotnet/coreclr/pulls?q=%5BLocal+GC%5D+in%3Atitle+is%3Apr)
* [Local GC 2.1.0 Issue Query](https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=%5BLocal%20GC%5D%20in%3Atitle%20is%3Aissue%20milestone%3A%222.1.0%22%20is%3Aopen)

cc @sergiy-k

**Comment by swgillespie** [comment]
Project is also updated: https://github.com/dotnet/coreclr/projects/3

**Comment by 4creators** [comment]
@swgillespie Seems that current status of Local GC project is more advanced than this issue indicates. Could it be possible to update this issue and project docs?
