### ISSUE TITLE
[RyuJIT] Improve SSA construction throughput

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#15108]
I have various pending work that improves `SsaBuilder` & co. memory usage and performance, maybe it's good to have an issue to track all that.

It looks like with the changes I have now (some already merged) the memory usage of SsaBuilder can be halved (perhaps even more) and there's also a drop in instruction retired of 0.5-1% (total instructions retired, can't measure just instructions retired during SSA construction).

- [x] Improve DF/IDF computation and storage (#14965)
- [x] Stop computing all IDFs up front (looks like there's simply no need to do this, `InsertPhiFunctions` can compute each IDF when needed and that allows reusing a single `BlkVector` for all IDFs) (#15146)
- [x] Improve SSA dom tree memory usage (#15006)
- [x] Eliminate duplicate SSA number bookkeeping (#15011)
- [x] Memory SSA should not reuse `LclSsaVarDsc`, the definition location information is not used and it wastes memory. A `ValueNumPair` is sufficient (possibly wrapped in a `SsaMemDef`) (#15011)
- [x] Remove `UNINIT_SSA_NUM` - it's not actually needed and it just wastes memory in the SSA arrays. (#15011)
- [x] Improve `fgExcludeFromSsa`. This is called many times and it's pretty large. `SsaBuilder` should call it once for every variable and then set a bit (looks like there are some spare bits available) in `LclVarDsc` that everyone else checks (#15351)
- [x] Stop creating SSA numbers (and VNs) for variables that are excluded from SSA. When `compInitMem` is true `SsaBuilder::RenameVariables` assigns SSA numbers to ALL variables (#15351)
- [x] Improve `SsaBuilder::TopologicalSort` (we can use a single stack and avoid some object copying) (#15200)
- [x] Improve SSA renaming (#15000)
- [x] Consider chaining PHIs and PHI_ARGs manually. Using `gtSetStmtInfo` and `fgSetStmtSeq` is expensive. (#20266)
- [x] Improve dom tree building & walking - it currently uses a hashtable, it's built a second time in copy prop for no reason, every time it is traversed memory may have to be allocated etc. (#27282)

Some of this (dom tree stuff, renaming) may apply to copy propagation as well since in its current form it mirrors SSA construction.

Once all of this is done it may be worth investigating extracting dominance related code into a separate class and merging with `fgComputeDoms` & co.

category:throughput
theme:ssa
skill-level:expert
cost:large

**Comment by mikedn** [comment]
@dotnet/jit-contrib Is anyone familiar with `IndirectAssignmentAnnotation`? 

It appears that this annotation is useless. If I change `fgMorphCopyBlock` to not create such annotations there are no framework diffs. At least in corelib, `SsaBuilder` never manages to create a def from these (more than 2000) annotations  because the corresponding local variable has its address taken and thus it is excluded from SSA. And if a SSA def is ever created from these annotations there's a chance that copy propagation will be broken, it tries to replicate SSA renaming but ignores these annotations. I assume that this can lead to copy propagation missing some SSA defs with unknown consequences.

**Comment by BruceForstall** [comment]
@mikedn Is this issue still accurate w.r.t. your plans for SSA construction throughput improvements? Looks like there's only one item left on your list.

**Comment by mikedn** [comment]
Yes, I'm going to look at the remaining item in the coming weeks. Though I suspect that I might end up discarding it, it's probably a trade off between deep trees and wide trees so probably not very useful.

**Comment by mikedn** [comment]
I think improving dom tree walking would be better served by an improved dom tree representation - put dom tree child/sibling links inside `BasicBlock` so we don't need to allocate any memory when (re)building the dom tree. 

We're building it 3 times now - once in `fgBuildDomTree` (or more than once? this ends up being called from `fgUpdateChangedFlowGraph` and this one is called multiple times), once before SSA rename and one more time before copy prop (not clear why, it's not supposed to have changed). And every time we allocate some memory - an array of `BasicBlockList` in `fgBuildDomTree` and a hashtable of `jitstd::vector` in SSA/copy prop.

Considering how JIT memory allocator works it's better to use e reusable data structure - the BBs themselves. The only potential trouble with this is that dominators aren't used in minopts mode and then the increased BB size (and they're pretty big as it is) will just be a waste.

**Comment by mikedn** [comment]
I think this can be closed now. Not to say that there's nothing left to improve but it's either:
* more flowgraph related rather than SSA related
* IR related - that may better wait for or be done as part of other IR improvements such as `ASG` removal

It would be interesting to know how much this actually improved but due to the long period of time this spanned it's problematic to attempt to revert everything an measure. So:

PR | PIN diff | Mem diff
--|--|--
14965 | 0.24% | 1.0%
15146 | 0.0% | 0.32%
15006 | 0.1% | 0.5%
15011 | 0.28% | 0.6%
15351 | 0.35% | 0.15%
15200 | 0.06% | 0.3%
15000 | 0.1% | 1.0%
20266 | 0.52% | 0.17%
27282 | 0.35% | 1.3%
27445 | 0.3% | 0.0%

If you could sum up percentages it would be 2.3% in PIN and 5.34% nraUsed. Since they're small percentages perhaps you can actually sum them up but there still may be interactions between changes that skew results on way or the other.

**Comment by BruceForstall** [comment]
Thanks for making all these improvements! It's great to see these continuous, incremental improvements. The JIT has had many efforts at throughput improvement and memory reduction over time, so it can be hard to squeeze out more, but it's nice to see when additional improvements are made.
