### ISSUE TITLE
Provide the ability to step into .Net Core Framework source using Visual Studio

### ISSUE THREAD

**Issue by noahfalk** [dotnet/coreclr#17488]
This issue tracks @raffaeler's request from https://github.com/dotnet/cli/issues/8872.

Likely this is the culmination of all our symbol publishing work tracked here:

- [x] Produce and upload symbols for Windows #10873
- [x] Produce and upload symbols for macOS #10872 
- [x] Produce and upload symbols for Linux #10868 

However, if there is anything additional that needs to be done to achieve source stepping, it should also be added as a dependency before this issue is closed.

**Comment by mikem8361** [comment]
Symbol indexing and uploading is now automated.
