### ISSUE TITLE
Unify remaining diverged microsoft\win32 types in corelib

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#17899]
We have reached the point that 60% of CoreCLR corelib code is shareable. We believe we can reasonably take this further, perhaps to 80% however much of the remaining reconciliation will take domain knowledge because the merges are not trivial.   See #9474

From a diff of `corert\src\system.private.corelib\src` and `coreclr\src\mscorlib\src` these are files whose implementations are yet to be unified. In some cases this will take care. In some happy cases the CoreRT code may just be a frozen old copy of the CoreCLR code from years ago in which case possibly resolution may be just "take coreclr". Once implementations have been reconciled, the shared copy should move under "shared" and the other copies deleted.

- [x]  	.\microsoft\win32\registry.cs
- [x]  	.\microsoft\win32\registryhive.cs
- [ ]  	.\microsoft\win32\registrykey.cs
- [ ]  	.\microsoft\win32\registrykey.windows.cs
- [x]  	.\microsoft\win32\registryoptions.cs
- [x]  	.\microsoft\win32\registryvaluekind.cs
- [x]  	.\microsoft\win32\registryvalueoptions.cs
- [x]  	.\microsoft\win32\registryview.cs
- [ ]  	.\microsoft\win32\throwhelper.cs
- [x]  	.\microsoft\win32\safehandles\saferegistryhandle.cs
- [x]  	.\microsoft\win32\safehandles\saferegistryhandle.windows.cs
- [ ]  	.\microsoft\win32\safehandles\safethreadpooliohandle.cs
- [x]  	.\microsoft\win32\safehandles\safewaithandle.cs
- [x]  	.\system\security\accesscontrol\registryrights.cs

**Comment by danmosemsft** [comment]
@maryamariyan this is a reasonable one to start with

**Comment by jkotas** [comment]
These are also duplicated under https://github.com/dotnet/corefx/tree/master/src/Microsoft.Win32.Registry/src

**Comment by filipnavara** [comment]
Seems like this one should be closed. None of the files exist in non-shared CoreCLR anymore.

**Comment by jkotas** [comment]
Yep
