### ISSUE TITLE
[Tracking] Status of known perf issues with tiered compilation

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#23201]
- [x] https://github.com/dotnet/coreclr/issues/19752 - Calls to virtual methods
  - Fixed by https://github.com/dotnet/coreclr/pull/21292, https://github.com/dotnet/coreclr/pull/21292#issuecomment-443090261 has relevant perf results
- [x] https://github.com/dotnet/coreclr/issues/19751 - Cold methods with hot loops
  - Several workarounds exist, issue description is updated with a list
  - Currently investigating the possibility of disabling tier 0 JIT for methods containing loops by default, collecting data
- [ ] https://github.com/dotnet/coreclr/issues/23060 - StringBuilder microbenchmark
  - Pending investigation
- [ ] https://github.com/dotnet/coreclr/issues/23620 - Regression in List<T>
  - Pending investigation

The following are currently are not targeted for 3.0:
- [x] https://github.com/dotnet/coreclr/issues/22998 - Performance repo microbenchmarks
  - The issue description contains a link to results. https://github.com/dotnet/performance/pull/247#issuecomment-460404981 contains some details about the investigation.
  - Most of the perf gaps appear to be due to the cold-method-with-hot-loops issue (https://github.com/dotnet/coreclr/issues/19751). A mode to disable tier 0 JIT was added and may be used for those microbenchmarks to resolve this issue, depending on the pending investigation for https://github.com/dotnet/coreclr/issues/19751.
  - Most of the larger remaining perf gaps appear to be noise of various types. Other than issues listed here, no new issues were found.
  - Deeper analysis would be useful, but weeding out the noise would involve a significant amount of work, will be scheduled as appropriate
- [ ] https://github.com/dotnet/coreclr/issues/20282 - Calls to non-virtual methods
  - Has not been a significant issue yet
- [ ] https://github.com/dotnet/coreclr/issues/22555 - Calls to methods with generic parameters
  - Has not been a significant issue yet
- [ ] https://github.com/dotnet/coreclr/issues/19757 - Background jitting overhead
  - Overhead typically occurs between startup and steady-state, has not been a significant issue yet
  - Typically the overhead is more than compensated for by the faster code that is generated
  - Overhead can be greater than the benefit when it's not as useful to tier-up the method. There are ideas floating on how to decrease the likelihood of these cases with more information from the JIT and R2R image, new heuristics, and improving current heuristics.
