### ISSUE TITLE
[EventPipe] A follow up to "Create the Concept of Multiple EventPipe Sessions #24417"

### ISSUE THREAD

**Issue by jorive** [dotnet/coreclr#24753]
### Fixme:

- [ ] EventPipe::Shutdown seems to be called more than once
- [ ] Review if it is safe to call `EventPipe::Disable` on `EventPipe::Shutdown` (`EventPipe::Disable` removes the session from the container we are iterating on `EventPipe::Shutdown`)
- [ ] Review why `EventPipe::WriteEvent` seems to be called after `EventPipe::Shutdown`
- [ ] Need to make thread safe iterating over the `EventPipe::s_pSessions` under `EventPipe::WriteEventInternal`
- [ ] Review EventPipe debug CONTRACTS: GC TRIGGER/NO TRIGGER, THROWS/NOTHROW, MODE PREEMTIVE/COOP/ANY, and made them more restrictive.
- [ ] Add appropriate contracts to `EventPipeThread::SetBufferList` and `EventPipeThread::SetWriteBuffer`. Currently there is a TRY/CATCH/IGNORE in those two methods because they are called from a method with a NOTHROW contract. Should we add STRESS_LOG to the catch block? What's appropriate?
- [ ] Provider Keywords' are of type INT64 and UINT64. We should make them all UINT64.
- [ ] Improve the `PlatformSleep` used on the `EventPipeSession::ThreadProc` method. It is a naïve sleep that could be changed to a sleep the "remaining time", so that events are written to the IPC in a timely manner.
- [ ] Add a mechanism that can notify EventPipe when there is an error on an active session, so it can be disposed properly from the list of active sessions.
- [ ] Review why "catch all" providers set NULL as provider name, when user needs to specify `"*"`
- [ ] Add better error handling to SampleProfiler: on `SampleProfiler::Initialize`, the call to `EventPipe::CreateProvider` could return NULL (potential AV lines below); on `SampleProfiler::Enable` the call to `LoadDependencies()` could fail and there is no error checking.

### Todo

- [ ] Consider adding a COMPLUS_* variable to control the SampleProfiler sampling rate (currently hardcoded). This would be for testing.
- [ ] Allow user input to set the `rundownEnabled` parameter for a session.
- [ ] Break the lock when doing `EventPipe::Disable`, otherwise disabling a session will be able to block all other sessions from doing work for a long time.
- [ ] On `EventPipe::DisableInternal` we send process info globally (to all active sessions). Maybe we could only send it to the session that it's been disabled (only once)?
- [ ] When calling `EventPipeConfiguration::Disable` we need to do a better job on reseting all keywords and levels for the remaining active sessions.
- [ ] Maybe revert back EventPipeSessionID to be address of the pointer instead of the bit mask: https://github.com/dotnet/coreclr/pull/24417#discussion_r286384780
