### ISSUE TITLE
System.Net Logging Tracking Items

### ISSUE THREAD

**Issue by josguil** [dotnet/coreclr#2483]
Tracking Items for https://github.com/dotnet/corefx/pull/5101

Formatting in *EventSource classes:
- [] Make constants have PascalCasing.
- [] Correctly separate arguments of methods in different lines (when needed).
- [] Add spaces needed in the attributes of the methods when not correctly aligned.
- [] New lines after if/else blocks (mainly after the IsEnabled check).

Dump Methods in SocketsEventSource:
- [] Analyse if the method type is necessary.
- [] Analyse if copying the buffer when it is received as an IntPtr to a byte [] is necessary.

Logging.cs class
- [] Look for all the references done to this class in all projects and change calls to hash methods instead to LoggingHash.
- [] Delete Logging.cs (in both S:\corefx\src\Common\src\System\Net\Logging AND S:\corefx\src\common\src\system\net) 

Keep in sync Localization:
-[] https://github.com/dotnet/corefx/issues/5126

**Comment by josguil** [comment]
This issue correspond to the corefx repo.
