### ISSUE TITLE
Separate GenTreeStmt from GenTree.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#25899]
This will allow us to save ~1% of Jit memory usage (according to my raw prototype), clean many noway_asserts, switches, and checks;
It will make code more readable and make statements more flexible. 

See discussion in https://github.com/dotnet/coreclr/pull/22963 (https://github.com/dotnet/coreclr/pull/22963#issuecomment-478165359).

The steps are:

- [x] Delete unused function and flags (addressed by https://github.com/dotnet/coreclr/pull/25886);
- [x] Separate ILGenOffset from Statements (#25898);
- [x] Do now reference GenTreeStmt as GenTree (#25898);
- [x] Separate bbTreeList and bbStmtList (#26092);
- [x] Do not inherit GenTreeStmt from GenTree (#26092);
- [ ] Massive renaming for the new Statement class and its fields;

Additional steps:

- [ ] Delete extra fields in stmt (like `getPrevStmt`, `IsPhiDefnStmt`);
- [x] Return void from `GenTreeStmt* fgInsertStmtSomewhere`;
- [x] Return debug number for statements; 
- [x] Retun a print function for statements;
- [ ] Think how to get rid of `bool compilerAdded`;
- [x] Add iterators.

category:implementation
theme:ir
skill-level:intermediate
cost:medium

**Comment by mikedn** [comment]
> This will allow us to save ~1% of Jit memory usage

Where do this savings come from? Since ILOffset still needs to be a GenTree it seems like we should end up in the same place in terms of memory usage.

**Comment by sandreenko** [comment]
> Where do this savings come from? Since ILOffset still needs to be a GenTree it seems like we should end up in the same place in terms of memory usage.

ILOffset becomes a small node (stmt is large now, probably without any reasons) and `Rationalizer::DoPhase()` creates ILOffsets only for `statement->gtStmtILoffsx != BAD_IL_OFFSET` that are rare.
If I grep for `gtNewStmt(GenTree* expr, IL_OFFSETX offset)` usages I see that only ~50% of calls set offset and many of the rest just copy them and also have an invalid value. 

So, as a result, we have less ILOffset and they are smaller.

**Comment by sandreenko** [comment]
From what I see in Release System.Private.CoreLib in my prototype where Stmt was separated from GenTree:
before:
```
  alloc size :   2417835906 (avg   78636 per method)
  ASTNode |  478665919 |  19.80%
```
after:
```
  alloc size :   2393040506 (avg   77830 per method)
  ASTNode |  451277623 |  18.86% (including stmts, I did not change their memory kind).
```
so the ratio is 1.0104.
but there were a few significant possibilities to improve that gain in the final change, probably up to 1.5%.

**Comment by BruceForstall** [comment]
What would you consider the disadvantages, if any?

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib

**Comment by sandreenko** [comment]
> What would you consider the disadvantages, if any?

- Review cost (it affects many lines of code);
- Possibly new bugs that could be introduced with this change (I have found several strange places, that I am going to fix, but looks like we do not have testing for these parts now);
- Additional field in BasicBlock (at least temporary until we are confident enough to use unions there).
