### ISSUE TITLE
Enable Ready2Run

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3349]
- [x] Enable Ready2Run compilation and run of repo tests in CI (https://github.com/dotnet/coreclr/issues/3707)
- [ ] Enable Ready2Run compilation and run of repo tests in Helix. (https://github.com/dotnet/coreclr/issues/3710)
- [ ] Enable Stress/GCStress for R2R tests (https://github.com/dotnet/coreclr/issues/3708)
- [ ] Enable Perf runs for R2R (https://github.com/dotnet/coreclr/issues/3709)
- [x] Enable SharedFramework (including Roslyn) R2R compilation and CoreFX test runs against it

We will start this work in RC2 and hence, the milestone.

**Comment by janvorli** [comment]
@gkhanna79 the ready to run tests that we have and that are part of the runtime tests are already run during each CI.

**Comment by gkhanna79** [comment]
@janvorli I have updated the Title to reflect the intent more accurately.

**Comment by janvorli** [comment]
Ah, makes sense

**Comment by gkhanna79** [comment]
Moved to RTM since all outstanding activities are targetted for the same.

**Comment by gkhanna79** [comment]
Closing this as invididual issues are tracking the activities.
