### ISSUE TITLE
Transition Repo for RTM

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3643]
- [x] Publish packages (tracked by this issue)
- [x] Publish symbol packages (tracked by #4321)
- [x] Enable Signing (tracked by #3019)
- [x] Enable Linux build definitions (tracked by this issue)
- [x] Enable versioning of binaries (tracked by #3559 and #3133)

**Comment by gkhanna79** [comment]
Closing since all associated work is complete.
