### ISSUE TITLE
[ARM64/Linux] Cross building CoreCLR ARM64 on Linux

### ISSUE THREAD

**Issue by lemmaa** [dotnet/coreclr#5450]
I ran into several problems during the cross build CoreCLR for ARM64 in linux machine.
I'm trying to record and solve the information here.
- [x] CMake initialization failure on ARM64 cross build (#5406)
- [x] Fix wrong filename, `DisasmARM64.cpp`, for case sensitive filesystem.  (#5448)
- [x] Fix compile error 'cannot be narrowed to type int' (#5452)
- [x] ~~Fix 'array index xx is past the end of the array' error. (#5460)~~
  - [x] Don't track LR as part of NV-Context (#5666)
  - [x] Fix `error: index must be an integer in range.` (#5682)
- [x] Fix 'error: 109 enumeration values not handled in switch' (#5493)
- [x] Disable not yet implemented features. (#5495)

**Comment by seanshpark** [comment]
#5452 landed.

**Comment by sdmaclea** [comment]
@jashook Looks like this one completed and shold be closed

**Comment by lemmaa** [comment]
@sdmaclea Yes, I close it. Thanks!
