### ISSUE TITLE
ARM64 GCStress: Failure Summary

### ISSUE THREAD

**Issue by kyulee1** [dotnet/coreclr#6068]
This is summary of all failures under `set COMPlus_GCStress=0x3`
- [ ] Test Failed #6060
- [x] Assert failure: !IsNull() #6062
- [x] Assert failure: EHCount > 0 #6064
- [x] Assert failure: ExceptionTracker::HasFrameBeenUnwoundByAnyActiveException(&m_crawl) #6122
- [x] Assert failure: pSpinLock->holding_thread == (Thread*)-1 #6143
- [ ] Timeout #6065

This is summary of all failures under `set COMPlus_GCStress=0xC`
Note some of failures are non-deterministic.
- [x] Assert failure: !pThread->HasPendingGCStressInstructionUpdate() #6057
- [ ] Assert failure: SanityCheck() #6058
- [ ] Assert failure: !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.") #6059
- [ ] Test Failed #6060
- [ ] AV in clr at this callstack #6061
- [x] Assert failure: !IsNull() #6062
- [ ] Assert failure: SyncTableEntry::GetSyncTableEntry()[sbIndex].m_Object == obj  #5674
- [x] Assert failure: EHCount > 0 #6064
- [ ] Timeout #6065
- [ ] Assert failure: m_alignpad == 0 #6066
- [ ] Assert failure: obj->GetGCSafeMethodTable ()->HasFinalizer () #6067

**Comment by jasonwilliams200OK** [comment]
Should there be separate labels for Windows-ARM64 and Unix-ARM64 as the implementations of .S and .ASM are different in src/vm. Besides, all these issues were tested on Windows ARM64 I presume and Unix ARM might not have these (but perhaps different issues)? Similarly when there is x86-64 issue, the OS name is called out in the issue and label doesn't explicitly specify the architecture.

**Comment by kyulee1** [comment]
I agree having separate for each OS and/or each architecture to make issues clearer.
I think the current convention here is somewhat historical. We started from Windows-x64, which does not have specific label. For non-Windows (e.g, Linux/OS X), or non-x64 (e.g, arm/arm64/x86) we have different label for them.

**Comment by sdmaclea** [comment]
@jashook Many of these holes will be fixed the PRs in flight.  As this summary is and will be out of date perhaps it should be closed.

**Comment by BruceForstall** [comment]
Closing this obsolete meta-issue.
