### ISSUE TITLE
[ARM32/Linux] CoreCLR building issues for ARM32 on Linux

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/coreclr#8549]
We have some issues for ARM 32bit cross building on Linux. Especially, we need to clear some of these tasks to enable core-setup for ARM32. (dotnet/core-setup#725)

Packages build
- [x] Update CoreCLR to generate nuget packages of CoreCLR (PR: #8421)
- [x] Enable CoreCLR Pipeline build support for Linux for Arm32 and publish packages (issue https://github.com/dotnet/coreclr/issues/8639)
- [x] Build `libcoreclrtraceptprovider.so` (issue #8684)
- [ ] Generate *.ni.dll files using x86 hosted crossgen (issue https://github.com/dotnet/coreclr/issues/8647)
- [ ] pass unit test

Fix build script for cross build
- [x] Fix build script for cross-architecture component (Issue: #8495 PR: #8646)

CI support
- [x] Update CI to use Docker images for ARM32 CI (issue: #9273,  #9445 PR: #10185)

**Comment by hseok-oh** [comment]
cc @chunseoklee @jyoungyun @idkiller 
@gkhanna79 @janvorli

**Comment by gkhanna79** [comment]
How does this relate, tracking wise, to https://github.com/dotnet/core-setup/issues/725?

**Comment by hseok-oh** [comment]
@gkhanna79 I also think not all of tasks in this issue are related to dotnet/core-setup#725. 

And we may generate package file for Linux ARM32 by task 1 (Update CoreCLR to generate nuget packages of CoreCLR). But we need additional tasks to generate more complete package. (such as `libcoreclrtraceptprovider.so` , `crossgen` and `*.ni.dll`)

**Comment by stevedesmond-ca** [comment]
I had previously noticed that libcoreclrtraceptprovider.so is explicitly ignored/removed from the things to build for non-Windows ARM...was this based on a previous assumption/requirement that is no longer true? I'm happy to pick that one up if no one else has.

As for the crossgen pieces, [here](https://github.com/stevedesmond-ca/dotnet-arm/blob/master/build) is how I was doing it, quick and dirty, though that requires sudo'ing, which is probably not the best way.

**Comment by gkhanna79** [comment]
@hseok-oh I would suggest we have a single issue to track all open items for Linux Arm32 E2E bringup so that it serves as a reference of the current status. Can you please reference these as "CoreCLR Arm32 issues" from https://github.com/dotnet/core-setup/issues/725 and use this issue as a central issue for all CoreCLR for Linux Arm32 issues?

**Comment by gkhanna79** [comment]
@stevedesmond-ca The repo builds clean with libcoreclrtraceptprovider.so for 16.04. However, it does not build clean for Ubuntu 14.04 and, hence, being excluded.

> requires sudo'ing, which is probably not the best way.

Yes, and it is blocker for automation to use that approach. Hence, we need to have a x86 hosted crossgen that generate Arm32 code so that it just runs in the natural expected manner.

**Comment by hseok-oh** [comment]
@gkhanna79 I updated dotnet/core-setup#725 and this issue. I agree with you.

**Comment by hqueue** [comment]
I also agree that this issue handle all CoreCLR related issues for Arm32 bringup.

@gkhanna79 what does "E2E" in "Arm32 E2E bringu" stand for?

**Comment by gkhanna79** [comment]
@hqueue E2E stands for End-to-End.

**Comment by hseok-oh** [comment]
@gkhanna79 is there need any more preparation for pipelining CoreCLR for ARM32 on Linux?

**Comment by gkhanna79** [comment]
@hseok-oh there are no changes required from you for that :) I will get the changes done in our infra.

**Comment by gkhanna79** [comment]
https://github.com/dotnet/core-setup/issues/725#issuecomment-274379440 explains the current status of CoreCLR Linux Arm32 pipeline build status.

**Comment by gkhanna79** [comment]
CoreCLR pipeline build is now publishing Arm32 (armhf) packages for Ubuntu 14.04 and Ubuntu 16.04 on myget! Here are the first set of packages that got published today from the repo:

https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.ubuntu.14.04-arm.Microsoft.NETCore.Runtime.CoreCLR

https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.ubuntu.16.04-arm.Microsoft.NETCore.Runtime.CoreCLR

**Comment by hqueue** [comment]
@hseok-oh Please add "Enable CI support for Linux Arm32" (https://github.com/dotnet/coreclr/pull/9445) to the list.

**Comment by hqueue** [comment]
@hseok-oh Please check "Update CI to use Docker images for ARM32 CI" as done :)

**Comment by BruceForstall** [comment]
@hseok-oh Is this issue still up-to-date and relevant?

**Comment by hseok-oh** [comment]
We can follow remain one issue (cross-crossgen) on it's issue. So I think this issue can be closed.
