### ISSUE TITLE
Remove redundant defines from native part of CoreCLR

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#9067]
From the native code, remove all defines that are always defined (across platforms, architectures, and flavors) both in the build infrastructure and from the code itself. 
Also remove all defines that are never defined again from the build infrastructure and the code itself.

See these two equivalent PR's already complete for the corelib. 
https://github.com/dotnet/coreclr/pull/9044
https://github.com/dotnet/coreclr/pull/9058

For managed code there was a tool to edit the code easily (see https://github.com/dotnet/coreclr/issues/8857). For native code such tools exist such as http://coan2.sourceforge.net/ -- it would be worth trying some before giving up and doing the edits manually.

**Comment by danmosemsft** [comment]
These are always defined in native (ie unconditionally set in clrdefinitions.cmake and not undefined elsewhere in makefile or code)

- [ ] _BLD_CLR
- [ ] DEBUGGING_SUPPORTED
- [ ] FEATURE_APPDOMAIN_RESOURCE_MONITORING
- [ ] FEATURE_ASYNC_IO
- [ ] FEATURE_COLLECTIBLE_TYPES
~~- [ ] FEATURE_CORECLR~~
~~- [ ] FEATURE_CORESYSTEM~~
- [ ] FEATURE_CORRUPTING_EXCEPTIONS
- [ ] FEATURE_EXCEPTION_NOTIFICATIONS
- [ ] FEATURE_EXCEPTIONDISPATCHINFO
- [ ] FEATURE_HOST_ASSEMBLY_RESOLVER
- [ ] FEATURE_ICASTABLE
- [ ] FEATURE_ISYM_READER
- [ ] FEATURE_LEGACYNETCF_DBG_HOST_CONTROL
- [ ] FEATURE_LOADER_OPTIMIZATION
- [ ] FEATURE_MAIN_CLR_MODULE_USES_CORE_NAME
- [ ] FEATURE_MANAGED_ETW_CHANNELS
- [ ] FEATURE_MERGE_CULTURE_SUPPORT_AND_ENGINE
- [ ] FEATURE_MULTICOREJIT
- [ ] FEATURE_NORM_IDNA_ONLY
- [ ] FEATURE_PREJIT
- [ ] FEATURE_RANDOMIZED_STRING_HASHING
- [ ] FEATURE_READYTORUN
- [ ] FEATURE_SPAN_OF_T
- [ ] FEATURE_STANDALONE_SN
- [ ] FEATURE_STRONGNAME_DELAY_SIGNING_ALLOWED
- [ ] FEATURE_STRONGNAME_MIGRATION
- [ ] FEATURE_SVR_GC
- [ ] FEATURE_SYMDIFF
- [ ] FEATURE_SYNCHRONIZATIONCONTEXT_WAIT
- [ ] FEATURE_SYNTHETIC_CULTURES
- [ ] FEATURE_USE_ASM_GC_WRITE_BARRIERS
- [ ] FEATURE_VERSIONING
- [ ] FEATURE_WINDOWSPHONE
- [ ] FEATURE_WINMD_RESILIENT 

Which do we want to eliminate?

**Comment by danmosemsft** [comment]
Conversely there are over 500 symbols referenced in native code #if statements but never defined (in makefile or code .. possibly in the managed build); 63 are FEATURE_XXX symbols: 

- [ ] FEATURE_APPDOMAINMANAGER_INITOPTIONS
- [ ] FEATURE_APPX_BINDER
- [ ] FEATURE_APTCA
- [ ] FEATURE_BASICFREEZE
- [ ] FEATURE_CASE_SENSITIVE_FILESYSTEM
- [ ] FEATURE_CER
- [ ] FEATURE_CLICKONCE
- [ ] FEATURE_CODEPAGES_FILE
- [ ] FEATURE_COMINTEROP_MANAGED_ACTIVATION
- [ ] FEATURE_COMINTEROP_REGISTRATION
- [ ] FEATURE_COMINTEROP_TLB_SUPPORT
- [ ] FEATURE_COMINTEROP_WINRT_DESKTOP_HOST
- [ ] FEATURE_COMPRESSEDSTACK
- [ ] FEATURE_COUNT_GC_WRITE_BARRIERS
- [ ] FEATURE_CRYPTO
- [ ] FEATURE_DBG_PUBLISH
- [ ] FEATURE_DBGIPC_TRANSPORT
- [ ] FEATURE_ENABLE_NO_RANGE_CHECKS
- [ ] FEATURE_FULL_NGEN
- [ ] FEATURE_FUSION
- [ ] FEATURE_IDENTITY_REFERENCE
- [ ] FEATURE_IMPERSONATION
- [ ] FEATURE_INCLUDE_ALL_INTERFACES
- [ ] FEATURE_INTERPRETER
- [ ] FEATURE_IPCMAN
- [ ] FEATURE_ISOSTORE
- [ ] FEATURE_ISOSTORE_LIGHT
- [ ] FEATURE_ITINSTRUCTION
- [ ] FEATURE_LAZY_COW_PAGES
- [ ] FEATURE_LEAK_CULTURE_INFO
- [ ] FEATURE_MDA
- [ ] FEATURE_METADATA_EMIT_ALL
- [ ] FEATURE_METADATA_PERF_STATS
- [ ] FEATURE_METADATA_STANDALNE_WINRT_RO
- [ ] FEATURE_METADATA_STANDALONE_WINRT
- [ ] FEATURE_METADATA_STANDALONE_WINRT_RO
- [ ] FEATURE_METADATA_VALIDATOR
- [ ] FEATURE_METHOD_RENTAL
- [ ] FEATURE_MIXEDMODE
- [ ] FEATURE_MULTIMODULE_ASSEMBLIES
- [ ] FEATURE_NATIVE_IMAGE_GENERATION
- [ ] FEATURE_NO_STRESSLOG
- [ ] FEATURE_NON_UNICODE_CODE_PAGES
- [ ] FEATURE_PERFMON
- [ ] FEATURE_PLI_INSTRUCTION
- [ ] FEATURE_PLS
- [ ] FEATURE_PROFAPI_ATTACH_DETACH
- [ ] FEATURE_REFLECTION_ONLY_LOAD
- [ ] FEATURE_REMOTING
- [ ] FEATURE_RWLOCK
- [ ] FEATURE_SERIALIZATION
- [ ] FEATURE_SINGLE_THREADED
- [ ] FEATURE_STACK_PROBE
- [ ] FEATURE_STRONGNAME_STANDALONE_WINRT
- [ ] FEATURE_STRUCTALIGN
- [ ] FEATURE_TRACELOGGING
- [ ] FEATURE_TYPEEQUIVALENCE
- [ ] FEATURE_UEF_CHAINMANAGER
- [ ] FEATURE_UNIX_AMR64_STRUCT_PASSING
- [ ] FEATURE_USE_LCID
- [ ] FEATURE_UTILCODE_NO_DEPENDENCIES
- [ ] FEATURE_WIN_DB_APPCOMPAT
- [ ] FEATURE_X509

[Full list](https://github.com/dotnet/coreclr/files/769160/always_undefined.txt)

All these could potentially allow code to be removed without too much difficulty. Which are worthwhile?

**Comment by danmosemsft** [comment]
@jkotas @gkhanna79

**Comment by jkotas** [comment]
I have checked the ones that should be no-brainer to remove.

**Comment by danmosemsft** [comment]
Removed all the checked ones, in the associated changes.
