### ISSUE TITLE
[x86/Linux] CI support for build using docker

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/coreclr#9903]
I hope to build x86/Linux in CI machine using docker. 

- build native code using x86 ubuntu docker container
- build managed code in x64 environment (cannot use dotnetcli in x86/linux)
- test using x86 ubuntu docker container

I succeeded building x86/Linux coreclr using this steps. (not test yet) If we use x86 docker images, the rootfs for x86 is needless.

To do this, we need x86 ubuntu docker image including packages to build and test. (maybe same packages for ubuntu-arm build). 

related issue: #9553 

CoreCLR
- [x] CI support: CoreCLR build (#10079)
- [ ] CI support: CoreCLR test 
- [ ] Use official docker image for CoreCLR build & test

CoreFX
- [x] CI support: CoreFX build (dotnet/corefx#17182)
- [ ] CI support: CoreFX test 
- [ ] Use official docker image for CoreFX build & test (dotnet/corefx#17601)

**Comment by hseok-oh** [comment]
cc/ @parjong @seanshpark @wateret @YongseopKim @gkhanna79

**Comment by gkhanna79** [comment]
Is x86 RootFS only required for U14.04 or even for 16.04?

**Comment by hseok-oh** [comment]
@gkhanna79 I think it will be enough using one of them. @parjong, Do you have any opinion about this?

**Comment by parjong** [comment]
@hseok-oh Any version is acceptable for me.

**Comment by hseok-oh** [comment]
We don't need RootFS to generate CoreCLR x86/linux if we have x86 ubuntu docker image. But, we should use RootFS to generate CoreFX. As a result, it seems we need x86 RootFS for x86/linux build.

**Comment by seanshpark** [comment]
I prefer U16.04

**Comment by gkhanna79** [comment]
CC @MichaelSimons

**Comment by MichaelSimons** [comment]
I'm not aware of any officially supported i386 Ubuntu Docker images.  Is there a proposal on what base images should be used?

**Comment by lemmaa** [comment]
Just for information, I'm using `ioft/i386-ubuntu` (https://hub.docker.com/r/ioft/i386-ubuntu/) as base image for i386 Ubuntu. It works well for dotnet core x86 dev & test.

**Comment by hseok-oh** [comment]
I'm also using same base image.

**Comment by janvorli** [comment]
https://hub.docker.com/r/i686/ubuntu/

**Comment by hseok-oh** [comment]
Now x86/Linux build in CI enabled. (not unittest yet)
You can run (on-demand run) debug, checked, and release build in CI using:
- test Ubuntu x86 Debug 
- test Ubuntu x86 Checked 
- test Ubuntu x86 Release 

Here is my test run and result.
https://github.com/dotnet/coreclr/pull/10138#issuecomment-286012710

**Comment by hseok-oh** [comment]
@parjong @seanshpark @wateret @YongseopKim
I'm trying to enable PAL test in CI now. Debug build passed pal tests, but checked build failed and release build showed timeout.

Checked (1 fail): https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_checked_ubuntu_prtest/4/
Release (timeout): https://ci.dot.net/job/dotnet_coreclr/job/master/job/x86_release_ubuntu_prtest/10/

FWIW, I have a plan to enable pal test for debug build first, and add for others when problem solved (maybe easy because it need just removing if-else in ci script).

**Comment by parjong** [comment]
@hseok-oh I'll take a look.

**Comment by danmosemsft** [comment]
@parjong @MichaelSimons who owns the next action here? Is this on track to be closed by 5/10 ZBB ? 

@weshaggard @markwilkie @Chrisboh

**Comment by MichaelSimons** [comment]
@parjong, @hseok-oh, @gkhanna79 - Is the remaining work to get a "trusted" x86 ubuntu image?  If so, I would like to see the product team define the Dockerfile.  I will take ownership of ensuring it gets built and pushed to microsoft/dotnet-buildtools-prereqs.

cc @dleeapho

**Comment by parjong** [comment]
@damnosemsft #10728 resolved checked build PAL test failures.

**Comment by hseok-oh** [comment]
@gkhanna79 Could you change this milestone to future work? This issue is related to x86/linux and I think it cannot be closed for 2.0.0.

**Comment by hseok-oh** [comment]
I'll prepare enabling Linux x86 TC pri2 test on CI.

**Comment by jashook** [comment]
This exists and can be closed.

**Comment by janvorli** [comment]
@jashook it looks like this issue was covering more things than the ones that are implemented - see the bullets in the description. Running tests in the CI and also moving to official docker images seem to be things that we still want.
I am reopening the issue.
